version: '3.1'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.2
    environment:
      - xpack.security.enabled=false
    networks:
      - ignitemt
    volumes:
      - ./.esdata:/usr/share/elasticsearch/data


  kibana:
    depends_on:
    - elasticsearch
    image: docker.elastic.co/kibana/kibana:6.1.2
    environment:
      - xpack.security.enabled=false
    ports:
      - 5601:5601
    networks:
      - ignitemt

networks:
  ignitemt:
    external: true
